# Generated by Django 2.0.2 on 2018-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20180204_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='poster',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
