# Generated by Django 2.0.2 on 2018-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_subject_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='daily_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
